// LOCALHOST Get all
### 
GET http://localhost:8080/contacts

// LOCALHOST Get specific ones
###
GET http://localhost:8080/contacts/644b153f6adc3b1dfb8c9b2f

###
GET http://localhost:8080/contacts/644b153f6adc3b1dfb8c9b30 

###
 GET http://localhost:8080/contacts/644b153f6adc3b1dfb8c9b31 



// Render
### 
GET https://xxxx/contacts 

 ### 
GET https://xxxx/contacts/644b153f6adc3b1dfb8c9b2f

 ### 
GET https://xxxx/contacts/644b153f6adc3b1dfb8c9b30

 ###
 GET https://xxxx/contacts/644b153f6adc3b1dfb8c9b31